import React, { useCallback, useContext, useEffect, useState } from 'react';
import { Button, Input, Select } from './Controls';
import { useAuth, can, RouteContext } from './contexts';
import { panel, Problem, nameOf } from './SalesWorkspace';

const fresh = module => ({ name: '', module, reportType: 'tabular', chartType: 'bar', columns: [], filters: [], groupBy: [], aggregations: [{ field: 'id', function: 'count' }], sortBy: [], limit: 500, isPublic: false });
const display = value => value == null ? '—' : typeof value === 'object' ? nameOf(value) : String(value);
const noValue = op => ['is_null', 'is_not_null', 'this_month', 'this_quarter', 'this_year'].includes(op);
const flatten = row => Object.fromEntries(Object.entries(row).flatMap(([key, value]) => key.startsWith('_') && value && typeof value === 'object' ? Object.entries(value).map(([field, n]) => [`${key.slice(1)} ${field}`, n]) : [[key, value]]));

export function ReportBuilderPage() {
  const { apiFetch, user, demoMode } = useAuth(); const { navigate } = useContext(RouteContext);
  const [metadata, setMetadata] = useState(null), [reports, setReports] = useState([]), [definition, setDefinition] = useState(fresh('deals'));
  const [result, setResult] = useState(null), [drill, setDrill] = useState(null), [error, setError] = useState(''), [notice, setNotice] = useState(''), [busy, setBusy] = useState(false);
  const [insights, setInsights] = useState(null);
  const load = useCallback(() => apiFetch('/reports').then(setReports), [apiFetch]);
  useEffect(() => { let alive = true; Promise.all([apiFetch('/reports/metadata'), apiFetch('/reports')]).then(([m, r]) => { if (!alive) return; setMetadata(m); setReports(r); const module = Object.keys(m.modules).find(k => can(user, k, 'read')); if (module && !can(user, 'deals', 'read')) setDefinition(fresh(module)); }).catch(e => alive && setError(e.message)); return () => { alive = false; }; }, [apiFetch, user]);
  useEffect(() => { if (can(user, 'deals', 'read')) apiFetch('/sales-workspace/insights').then(setInsights).catch(e => setError(e.message)); }, [apiFetch, user]);
  const fields = metadata?.modules?.[definition.module]?.fields || {};
  const options = Object.entries(fields).map(([value, f]) => ({ value, label: f.label }));
  const put = key => value => { setDefinition(d => ({ ...d, [key]: value })); setResult(null); setDrill(null); };
  const prepared = def => {
    const definitions = metadata?.modules?.[def.module]?.fields || {};
    const filters = def.filters.map(f => {
      if (definitions[f.field]?.type !== 'number' || noValue(f.operator)) return f;
      const values = ['in', 'not_in', 'between'].includes(f.operator) ? (Array.isArray(f.value) ? f.value : String(f.value).split(',')) : [f.value];
      if (values.some(v => String(v).trim() === '' || !Number.isFinite(Number(v)))) throw new Error('Numeric filters need valid numbers.');
      return { ...f, value: ['in', 'not_in', 'between'].includes(f.operator) ? values.map(Number) : Number(values[0]) };
    });
    // Never add amounts in different currencies into one report group.
    const monetary = def.module === 'deals' && def.reportType === 'summary' && def.aggregations.some(a => a.field === 'value' && a.function !== 'count');
    return { ...def, filters, groupBy: monetary ? [...new Set([...def.groupBy, 'currency'])] : def.groupBy };
  };
  const run = async (def = definition, isDrill = false) => {
    setBusy(true); setError(''); setNotice('');
    try { const ready = prepared(def); const data = await apiFetch('/reports/execute', { method: 'POST', body: ready }); if (data.summary?.error) throw new Error(data.summary.error); if (!isDrill) setDefinition(ready); isDrill ? setDrill(data) : (setResult(data), setDrill(null)); }
    catch (e) { setError(e.message); } finally { setBusy(false); }
  };
  const save = async () => {
    if (!definition.name.trim()) { setError('Give this report a name.'); return; }
    setBusy(true); setError('');
    try { const own = definition.id && definition.createdById === user.id; const d = await apiFetch(own ? `/reports/${definition.id}` : '/reports', { method: own ? 'PUT' : 'POST', body: prepared(definition) }); setDefinition(d); await load(); setNotice(own ? 'Report updated.' : 'Report saved.'); }
    catch (e) { setError(e.message); } finally { setBusy(false); }
  };
  const preset = (name, groupBy, aggregations, filters = []) => { setDefinition({ ...fresh('deals'), name, reportType: 'summary', groupBy, aggregations, filters }); setResult(null); setDrill(null); };
  const grouped = result?.summary?.type === 'grouped' ? result.summary.data : [];
  const totals = result?.summary?.type === 'totals' ? [flatten(result.summary.data || {})] : [];
  const tableRows = drill?.rows || (definition.reportType === 'summary' ? grouped.map(flatten).concat(totals) : result?.rows || []);
  const tableColumns = tableRows.length ? Object.keys(tableRows[0]).filter(k => k !== 'id') : [];
  const cell = (key, value) => (drill || result)?.labels?.[key]?.[value] || display(value);
  const drillInto = row => run({ ...definition, reportType: 'tabular', filters: [...definition.filters, ...definition.groupBy.map(field => ({ field, operator: row[field] == null ? 'is_null' : 'equals', value: row[field] }))] }, true);
  const exportRows = () => {
    const escape = value => { let v = display(value); if (/^[=+@\-\t\r]/.test(v)) v = `'${v}`; return `"${v.replaceAll('"', '""')}"`; };
    const csv = [tableColumns, ...tableRows.map(r => tableColumns.map(k => r[k]))].map(r => r.map(escape).join(',')).join('\r\n');
    const url = URL.createObjectURL(new Blob(['\uFEFF', csv], { type: 'text/csv;charset=utf-8' })); const a = document.createElement('a'); a.href = url; a.download = 'sales-report.csv'; a.click(); URL.revokeObjectURL(url);
  };
  if (!metadata) return <><h1 className="text-xl font-bold">Reports</h1><Problem message={error} /><p>Loading report builder…</p></>;
  return <div className="space-y-4"><h1 className="text-xl font-bold">Reports</h1><p className="text-sm text-[#7E8598]">Build a report from records you can access. Sharing a definition never shares extra record access.</p>
    {insights && <section className={panel} aria-label="Sales performance"><h2 className="font-semibold mb-3">Sales performance · all visible deals</h2><div className="grid sm:grid-cols-3 gap-3"><div>Win rate<p className="text-xl font-bold">{insights.winRate}%</p><span className="text-xs">Won ÷ closed deals</span></div><div>Average sales cycle<p className="text-xl font-bold">{insights.salesCycleDays == null ? 'Not enough history' : `${insights.salesCycleDays} days`}</p><span className="text-xs">Creation to last recorded Closed Won move ({insights.cycleSample} deals)</span></div><div>Closed outcomes<p>{insights.won} won · {insights.lost} lost</p></div></div><h3 className="mt-4 text-sm font-semibold">Observed stage progression</h3><p className="text-xs text-[#7E8598] mb-2">Deals with a recorded visit to each stage; the percentage reached the next stage at any time. Skipped stages and missing history are not inferred.</p><div className="flex flex-wrap gap-4">{insights.stages.map(s => <div key={s.stage} className="text-sm">{s.stage}<p>{s.visited} visited{s.conversion == null ? '' : ` · ${s.conversion}% reached ${s.next}`}</p></div>)}</div></section>}
    <div className="flex flex-wrap gap-2">{can(user, 'deals', 'read') && <><Button variant="secondary" onClick={() => preset('Pipeline by stage and currency', ['stage', 'currency'], [{ field: 'id', function: 'count' }, { field: 'value', function: 'sum' }])}>Pipeline report</Button><Button variant="secondary" onClick={() => preset('Rep performance by currency', ['ownerId', 'currency'], [{ field: 'id', function: 'count' }, { field: 'value', function: 'sum' }])}>Rep performance</Button><Button variant="secondary" onClick={() => preset('Win and loss reasons', ['stage', 'lossReason'], [{ field: 'id', function: 'count' }], [{ field: 'stage', operator: 'in', value: ['Closed Won', 'Closed Lost'] }])}>Win/loss report</Button></>}</div>
    <div className="grid lg:grid-cols-[15rem_1fr] gap-4"><aside className={panel}><h2 className="font-semibold">Saved reports</h2><Button variant="secondary" className="my-3" onClick={() => { setDefinition(fresh(definition.module)); setResult(null); setDrill(null); }}>New report</Button><ul className="space-y-2">{reports.filter(r => can(user, r.module, 'read')).map(r => <li key={r.id}><button className="text-left text-sm text-[#F5A623]" onClick={() => { setDefinition({ ...fresh(r.module), ...r }); setResult(null); setDrill(null); }}>{r.name}{r.isPublic ? ' · shared' : ''}</button></li>)}</ul></aside>
    <section className={`${panel} space-y-4`} aria-label="Report definition"><div className="grid sm:grid-cols-3 gap-3"><Input label="Report name" value={definition.name} onChange={put('name')} /><Select label="Module" value={definition.module} options={Object.keys(metadata.modules).filter(k => can(user, k, 'read')).map(value => ({ value, label: metadata.modules[value].label }))} onChange={module => { setDefinition({ ...fresh(module), name: definition.name }); setResult(null); setDrill(null); }} /><Select label="Report type" value={definition.reportType} options={['tabular', 'summary']} onChange={put('reportType')} /></div>
      <fieldset><legend className="text-sm font-semibold mb-2">Columns (none selected means all available columns)</legend><div className="flex flex-wrap gap-x-4 gap-y-2">{options.filter(f => f.value !== 'id').map(f => <label key={f.value} className="text-xs flex gap-1"><input type="checkbox" checked={definition.columns.some(c => c.field === f.value)} onChange={e => put('columns')(e.target.checked ? [...definition.columns, { field: f.value }] : definition.columns.filter(c => c.field !== f.value))} />{f.label}</label>)}</div></fieldset>
      <fieldset><legend className="text-sm font-semibold mb-2">Filters · all must match</legend><div className="space-y-2">{definition.filters.map((filter, i) => { const change = (key, value) => put('filters')(definition.filters.map((f, j) => j === i ? { ...f, [key]: value } : f)); return <div key={i} className="grid sm:grid-cols-[1fr_1fr_1fr_auto] gap-2"><Select label={`Filter ${i + 1} field`} value={filter.field} options={options} onChange={v => change('field', v)} /><Select label={`Filter ${i + 1} operator`} value={filter.operator} options={metadata.operators} onChange={v => change('operator', v)} />{!noValue(filter.operator) ? <Input label={`Filter ${i + 1} value`} value={Array.isArray(filter.value) ? filter.value.join(',') : filter.value} onChange={v => change('value', v)} placeholder={filter.operator.includes('between') ? 'Start, end' : 'Value'} /> : <span />}<Button variant="secondary" onClick={() => put('filters')(definition.filters.filter((_, j) => j !== i))}>Remove filter {i + 1}</Button></div>; })}</div><Button variant="secondary" className="mt-2" onClick={() => put('filters')([...definition.filters, { field: options[0]?.value, operator: 'equals', value: '' }])}>Add filter</Button></fieldset>
      {definition.reportType === 'summary' && <><fieldset><legend className="text-sm font-semibold mb-2">Group by</legend><div className="flex flex-wrap gap-3">{options.filter(f => fields[f.value].type !== 'date').map(f => <label className="text-xs flex gap-1" key={f.value}><input type="checkbox" checked={definition.groupBy.includes(f.value)} onChange={e => put('groupBy')(e.target.checked ? [...definition.groupBy, f.value] : definition.groupBy.filter(k => k !== f.value))} />{f.label}</label>)}</div></fieldset><div className="space-y-2">{definition.aggregations.map((a, i) => <div key={i} className="flex flex-wrap items-end gap-2"><Select label={`Measure ${i + 1}`} value={a.function} options={metadata.aggregationFunctions} onChange={v => put('aggregations')(definition.aggregations.map((x, j) => j === i ? { ...x, function: v, field: v === 'count' ? 'id' : options.find(o => fields[o.value].type === 'number')?.value || 'id' } : x))} /><Select label={`Measure ${i + 1} field`} value={a.field} options={a.function === 'count' ? options : options.filter(f => fields[f.value].type === 'number')} onChange={v => put('aggregations')(definition.aggregations.map((x, j) => j === i ? { ...x, field: v } : x))} /><Button variant="secondary" onClick={() => put('aggregations')(definition.aggregations.filter((_, j) => j !== i))}>Remove measure {i + 1}</Button></div>)}</div><Button variant="secondary" onClick={() => put('aggregations')([...definition.aggregations, { field: 'id', function: 'count' }])}>Add measure</Button><Select label="Chart" value={definition.chartType || 'bar'} options={[{ value: 'bar', label: 'Bar chart' }, { value: 'none', label: 'Table only' }]} onChange={put('chartType')} /></>}
      <div className="flex flex-wrap items-end gap-3"><Select label="Sort by" value={definition.sortBy[0]?.field || 'createdAt'} options={options} onChange={v => put('sortBy')([{ field: v, direction: definition.sortBy[0]?.direction || 'desc' }])} /><Select label="Direction" value={definition.sortBy[0]?.direction || 'desc'} options={['asc', 'desc']} onChange={v => put('sortBy')([{ field: definition.sortBy[0]?.field || 'createdAt', direction: v }])} /><Select label="Maximum detail rows" value={String(definition.limit || 500)} options={['100', '500', '1000']} onChange={v => put('limit')(Number(v))} /></div>
      <label className="flex gap-2 text-sm"><input type="checkbox" checked={definition.isPublic} onChange={e => put('isPublic')(e.target.checked)} />Share report definition with everyone</label><div className="flex gap-2"><Button disabled={busy} onClick={() => run()}>Run report</Button>{!demoMode && <Button variant="secondary" disabled={busy} onClick={save}>{definition.id && definition.createdById === user.id ? 'Save changes' : 'Save report'}</Button>}</div>
    </section></div><Problem message={error} />{notice && <p role="status">{notice}</p>}
    {result && <section className={panel} aria-label="Report results"><div className="flex flex-wrap justify-between gap-3"><h2 className="font-semibold">{drill ? 'Matching records' : 'Results'} · {drill?.totalCount ?? result.totalCount} records</h2><div className="flex gap-2">{drill && <Button variant="secondary" onClick={() => setDrill(null)}>Back to summary</Button>}<Button variant="secondary" onClick={exportRows} disabled={!tableRows.length}>Export displayed rows</Button></div></div>
      {!drill && grouped.length > 0 && definition.chartType === 'bar' && <div className="space-y-2 my-4" aria-label="Report chart">{grouped.slice(0, 50).map((row, i) => { const a = definition.aggregations[0]; const value = Number(row[`_${a.function}`]?.[a.field] || 0); const max = Math.max(1, ...grouped.map(r => Math.abs(Number(r[`_${a.function}`]?.[a.field] || 0)))); return <button key={i} className="block w-full text-left text-sm" onClick={() => drillInto(row)}><span>{definition.groupBy.map(k => cell(k, row[k])).join(' · ')}: {value.toLocaleString()}</span><span className="block h-3 rounded bg-[#F5A623]" style={{ width: `${Math.max(1, Math.abs(value) / max * 100)}%` }} /></button>; })}{grouped.length > 50 && <p>Chart shows the first 50 groups; the table includes all groups.</p>}</div>}
      <div className="overflow-x-auto mt-3"><table className="w-full text-sm"><thead><tr>{tableColumns.map(k => <th key={k} className="p-2 text-left">{fields[k]?.label || k}</th>)}<th>Open</th></tr></thead><tbody>{tableRows.map((row, i) => <tr key={row.id || i} className="border-t border-[#182550]">{tableColumns.map(k => <td key={k} className="p-2">{cell(k, row[k])}</td>)}<td>{row.id ? <Button variant="secondary" onClick={() => navigate(definition.module, row.id)}>Open record</Button> : grouped[i] && <Button variant="secondary" onClick={() => drillInto(grouped[i])}>View records</Button>}</td></tr>)}</tbody></table></div>
      <p className="text-xs text-[#7E8598] mt-3">{tableRows.length} rows displayed. Detail results are limited to {definition.limit || 500}; use filters to narrow larger results.</p>
    </section>}
  </div>;
}
