import React, { useCallback, useContext, useEffect, useState } from 'react';
import { Button, Input, Select, TextArea } from './Controls';
import { useAuth, can, RouteContext } from './contexts';
import { RecordPicker } from './SalesWorkflows';
import { panel, Problem, Pager, rowsOf, dateLabel } from './SalesWorkspace';

const signature = f => JSON.stringify({ name: f?.name, description: f?.description, steps: f?.steps });
const blank = () => ({ name: '', description: '', status: 'Draft', steps: [] });
const stepsOf = s => { try { return Array.isArray(s.steps) ? s.steps : JSON.parse(s.steps || '[]'); } catch { return []; } };
export function SequenceBuilderPage() {
  const { apiFetch, user, demoMode } = useAuth(); const { recordId, navigate } = useContext(RouteContext);
  const [sequences, setSequences] = useState([]), [total, setTotal] = useState(0), [page, setPage] = useState(1);
  const [savedSignature, setSavedSignature] = useState('');
  const [form, setForm] = useState(null), [templates, setTemplates] = useState([]), [delivery, setDelivery] = useState(null);
  const [enrollments, setEnrollments] = useState(null), [enrollPage, setEnrollPage] = useState(1);
  const [peopleModule, setPeopleModule] = useState(can(user, 'contacts', 'read') ? 'contacts' : 'leads'), [personId, setPersonId] = useState(null), [people, setPeople] = useState([]);
  const [busy, setBusy] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState('');
  const editable = !demoMode && can(user, 'emails', 'edit');
  const load = useCallback(() => apiFetch(`/sequences?limit=25&page=${page}`).then(d => { setSequences(d.data); setTotal(d.total); }), [apiFetch, page]);
  const loadEnrollments = useCallback(id => apiFetch(`/sequences/${id}/enrollments?page=${enrollPage}`).then(setEnrollments), [apiFetch, enrollPage]);
  useEffect(() => { load().catch(e => setError(e.message)); }, [load]);
  useEffect(() => { Promise.all([apiFetch('/emails/templates/all'), apiFetch('/sequences/delivery/status')]).then(([t, d]) => { setTemplates(rowsOf(t)); setDelivery(d); }).catch(e => setError(e.message)); }, [apiFetch]);
  useEffect(() => { let cancelled = false; setError(''); setPeople([]); setPersonId(null); if (!recordId || recordId === 'new') { setForm(recordId === 'new' ? blank() : null); setEnrollments(null); return; } apiFetch(`/sequences/${recordId}`).then(s => { if (!cancelled) { const loaded = { ...s, steps: stepsOf(s) }; setForm(loaded); setSavedSignature(signature(loaded)); } }).catch(e => !cancelled && setError(e.message)); return () => { cancelled = true; }; }, [apiFetch, recordId]);
  useEffect(() => { if (recordId && recordId !== 'new') loadEnrollments(recordId).catch(e => setError(e.message)); }, [recordId, loadEnrollments]);
  const perform = async action => { if (busy) return; setBusy(true); setError(''); setNotice(''); try { await action(); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  const save = () => perform(async () => { const body = { name: form.name, description: form.description, steps: form.steps.map((s, order) => ({ ...s, order, delayDays: Number(s.delayDays) })) }; const s = await apiFetch(form.id ? `/sequences/${form.id}` : '/sequences', { method: form.id ? 'PUT' : 'POST', body }); const saved = { ...s, steps: stepsOf(s) }; setForm(saved); setSavedSignature(signature(saved)); navigate('sequences', s.id); await load(); setNotice('Sequence saved.'); });
  const status = action => perform(async () => { await apiFetch(`/sequences/${form.id}/${action}`, { method: 'POST', body: {} }); const s = await apiFetch(`/sequences/${form.id}`); setForm(f => ({ ...f, status: s.status })); await load(); setNotice(action === 'activate' ? 'Sequence activated. Due email is sent by the scheduled worker when mail is configured.' : 'Sequence paused.'); });
  const updateStep = (i, key, value) => setForm(f => ({ ...f, steps: f.steps.map((s, j) => j === i ? { ...s, [key]: value } : s) }));
  const reorder = (i, delta) => setForm(f => { const steps = [...f.steps]; [steps[i], steps[i + delta]] = [steps[i + delta], steps[i]]; return { ...f, steps }; });
  return <div className="space-y-4"><div className="flex justify-between"><h1 className="text-xl font-bold">Sequences</h1>{editable && <Button onClick={() => { navigate('sequences', 'new'); setForm(blank()); setEnrollments(null); setNotice(''); }}>New sequence</Button>}</div>
    {delivery && !delivery.configured && <div className={panel}>Email sending is not configured. You can prepare sequences; they will not send until the administrator configures outgoing mail.</div>}
    <Problem message={error} />{notice && <p role="status">{notice}</p>}
    <div className="grid lg:grid-cols-[16rem_1fr] gap-4"><aside className={panel}><ul className="space-y-3">{sequences.map(s => <li key={s.id}><button className="text-left text-[#F5A623]" onClick={() => { setEnrollPage(1); navigate('sequences', s.id); }}>{s.name}</button><p className="text-xs text-[#7E8598]">{s.status} · {s.totalSteps} steps · {s.enrolledCount} enrollments</p></li>)}</ul><Pager page={page} total={total} onChange={setPage} /></aside>
      {form ? <div className="space-y-4"><section className={`${panel} space-y-3`} aria-label="Sequence editor"><Input label="Sequence name" value={form.name} onChange={name => setForm(f => ({ ...f, name }))} disabled={!editable} /><TextArea label="Description" disabled={!editable} value={form.description} onChange={description => setForm(f => ({ ...f, description }))} /><p className="text-sm">Status: {form.status}. Save changes before activating. Existing active enrollments must be removed before changing their steps.</p>
        {form.steps.map((s, i) => <fieldset key={i} className="border border-[#182550] rounded-lg p-3 space-y-3"><legend className="text-sm font-semibold">Step {i + 1}</legend><Input label={`Step ${i + 1} delay (days)`} type="number" min="0" max="365" value={s.delayDays ?? 0} onChange={v => updateStep(i, 'delayDays', v)} disabled={!editable} /><Select label={`Step ${i + 1} template`} value={s.templateId || ''} options={templates.map(t => ({ value: t.id, label: t.name }))} placeholder="Write an email below" onChange={id => { const t = templates.find(t => t.id === id); setForm(f => ({ ...f, steps: f.steps.map((step, j) => j === i ? { ...step, templateId: id || null, subject: t?.subject || step.subject || '', body: t?.body || step.body || '' } : step) })); }} disabled={!editable} /><Input label={`Step ${i + 1} subject`} value={s.subject} onChange={v => updateStep(i, 'subject', v)} disabled={!editable} /><TextArea label={`Step ${i + 1} email body`} disabled={!editable} value={s.body} onChange={v => updateStep(i, 'body', v)} rows={5} />
          {editable && <div className="flex gap-2"><Button variant="secondary" disabled={i === 0} onClick={() => reorder(i, -1)}>Move up</Button><Button variant="secondary" disabled={i === form.steps.length - 1} onClick={() => reorder(i, 1)}>Move down</Button><Button variant="secondary" onClick={() => setForm(f => ({ ...f, steps: f.steps.filter((_, j) => j !== i) }))}>Remove step {i + 1}</Button></div>}
        </fieldset>)}
        {editable && <div className="flex flex-wrap gap-2"><Button variant="secondary" onClick={() => setForm(f => ({ ...f, steps: [...f.steps, { delayDays: f.steps.length ? 2 : 0, subject: '', body: '' }] }))}>Add email step</Button><Button disabled={busy || !form.name.trim()} onClick={save}>Save sequence</Button>{form.id && <Button variant="secondary" disabled={busy || (form.status !== 'Active' && signature(form) !== savedSignature)} onClick={() => status(form.status === 'Active' ? 'pause' : 'activate')}>{form.status === 'Active' ? 'Pause sequence' : 'Activate sequence'}</Button>}</div>}
      </section>
      {form.id && <section className={`${panel} space-y-3`} aria-label="Sequence enrollments"><h2 className="font-semibold">Enrollments</h2>{editable && <><Select label="Enroll from" value={peopleModule} options={['contacts', 'leads'].filter(m => can(user, m, 'read'))} onChange={v => { setPeopleModule(v); setPersonId(null); }} /><RecordPicker module={peopleModule} label="Person" value={personId} onChange={(id, row) => { setPersonId(id); if (id && row) setPeople(p => p.some(x => x.id === id) ? p : [...p, { id, module: peopleModule, label: `${row.firstName} ${row.lastName}` }]); }} /><ul className="flex flex-wrap gap-2">{people.map(p => <li key={p.id}><Button variant="secondary" onClick={() => setPeople(all => all.filter(x => x.id !== p.id))}>{p.label} ×</Button></li>)}</ul><Button disabled={busy || !people.length || form.status !== 'Active'} onClick={() => perform(async () => { const result = await apiFetch(`/sequences/${form.id}/enroll`, { method: 'POST', body: { contactIds: people.filter(p => p.module === 'contacts').map(p => p.id), leadIds: people.filter(p => p.module === 'leads').map(p => p.id) } }); setNotice(`${result.enrolled} enrolled; ${result.skipped} already active.`); setPeople([]); setPersonId(null); await loadEnrollments(form.id); await load(); })}>Enroll selected people</Button></>}
        <p className="text-xs text-[#7E8598]">Activation and enrollment authorize future scheduled email. Only people you can access are listed below.</p>
        {(enrollments?.data || []).map(e => <div key={e.id} className="border-t border-[#182550] py-3"><div className="flex flex-wrap justify-between gap-2"><div><button className="text-left text-[#F5A623]" onClick={() => navigate(e.contactId ? 'contacts' : 'leads', e.contactId || e.leadId)}>{e.person?.firstName} {e.person?.lastName} · {e.person?.email}</button><p className="text-sm">{e.status} · Step {Math.min(e.currentStep + 1, form.steps.length)} of {form.steps.length} · Next {dateLabel(e.nextSendAt)}</p>{e.lastError && <p className="text-xs text-[#F87171]">{e.lastError}</p>}{e.lastSentAt && <p className="text-xs">Last sent {dateLabel(e.lastSentAt)}</p>}</div>{editable && e.status === 'Active' && <Button variant="secondary" disabled={busy} onClick={() => perform(async () => { await apiFetch(`/sequences/${form.id}/unenroll`, { method: 'POST', body: { enrollmentId: e.id } }); await loadEnrollments(form.id); await load(); })}>Stop enrollment</Button>}</div></div>)}
        <Pager page={enrollPage} total={enrollments?.total || 0} onChange={setEnrollPage} />
      </section>}</div> : <div className={panel}>Choose a sequence or create one to start.</div>}
    </div>
  </div>;
}
